apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-trigger-template
  namespace: iap-cicd-pipelines
spec:
  params:
    - description: The git repository url
      name: git-url
    - description: The git branch name
      name: git-branch
    - description: commit id as a image tag
      name: image
    - description: repository name
      name: repo-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-$(tt.params.repo-name)-
      spec:
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-branch
            value: $(tt.params.git-branch)
          - name: image
            value: $(tt.params.image)
          - name: repo-name
            value: $(tt.params.repo-name)
        pipelineRef:
          name: iap-cicd-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              metadata:
                name: shared-workspace-pvc
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi
          - name: gitops-workspace
            volumeClaimTemplate:
              metadata:
                name: gitops-workspace-pvc
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi

