apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-deployment-2
  namespace: demo-application
spec:
  params:
    - name: tag
      type: string
    - name: repo-name
      type: string
  steps:
    - image: 'alpine/git:v2.26.2'
      name: update-values-yaml
      resources: {}
      script: >
        #!/usr/bin/env sh

        set -e


        git config --global user.email "cicd-pipeline@redhat.com"

        git config --global user.name "cicd-pipeline"

        rm -rf project

        git clone -b main https://github.com/manendra88/applicationyamls.git 
        project

        cd project/helm/$(inputs.params.repo-name)

        echo "Updating yaml"

        cat -n values.yaml

        sed -i "s#tag: \"[a-zA-Z0-9|.]*\"#tag: \"$(inputs.params.tag)\"#"
        values.yaml

        cat values.yaml

        git add -u

        git commit -m "[tekton] updating deployment"

        git push
      workingDir: $(workspaces.gitops-workspace.path)
  workspaces:
    - name: gitops-workspace

