apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "demo-application.fullname" . }}
  labels:
    {{- include "demo-application.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.customHost }}
  port:
    targetPort: {{ .Values.route.targetPort }}
  to:
    kind: Service
    name: {{ include "demo-application.fullname" . }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
