apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "demp-application.fullname" . }}
  labels:
    {{- include "demo-application.labels" . | nindent 4 }}
spec:
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ include "demo-application.fullname" . }}
    weight: 100
  wildcardPolicy: None
